export const tag = ["decor", "fashion", "men", "women", "cosmetics", "furniture", "perfumes", "wearable"];
export  const tagFull = ["all categories", "decor", "fashion", "men", "women", "cosmetics", "furniture", "perfumes", "wearable"];
export  const fakeProduct = [
    {
      id: "1",
      productId: 21,
      uid: "Product1_STK",
      name: "Product1",
      adminId: "SKT",
      price: "19.00",
      priceDiscount: "15.30",
      discountPercent: "-10%",
      isNew: true,
      urlImage: "/product/p1.jpg",
      urlImageHover: "/product/p2.jpg",
    },
    {
      id: "2",
      productId: 22,
      uid: "Product2_STK",
      name: "Product2",
      adminId: "SKT",
      price: "20.00",
      priceDiscount: "10.00",
      discountPercent: "-50%",
      isNew: false,
      urlImage: "/product/p2.jpg",
      urlImageHover: "/product/p3.jpg",
    },
    {
      id: "3",
      productId: 23,
      uid: "Product3_STK",
      name: "Product3",
      adminId: "SKT",
      price: "20.00",
      // priceDiscount: "16.00",
      // discountPercent :"-20%",
      isNew: true,
      urlImage: "/product/p3.jpg",
      urlImageHover: "/product/p4.jpg",
    },
    {
      id: "4",
      productId: 24,
      uid: "Product4_STK",
      name: "Product4",
      adminId: "SKT",
      price: "20.00",
      priceDiscount: "18.00",
      discountPercent: "-12%",
      isNew: false,
      urlImage: "/product/p4.jpg",
      urlImageHover: "/product/p5.jpg",
    },

];